# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.o_data_query_options_currency import ODataQueryOptionsCurrency  # noqa: E501
from swagger_client.rest import ApiException


class TestODataQueryOptionsCurrency(unittest.TestCase):
    """ODataQueryOptionsCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataQueryOptionsCurrency(self):
        """Test ODataQueryOptionsCurrency"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.o_data_query_options_currency.ODataQueryOptionsCurrency()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
