# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.comments_api import CommentsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCommentsApi(unittest.TestCase):
    """CommentsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.comments_api.CommentsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_comments_add_comment(self):
        """Test case for comments_add_comment

        Agregar comentario  # noqa: E501
        """
        pass

    def test_comments_get(self):
        """Test case for comments_get

        Listar comentarios por external ID  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
