# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_profile_api import UserProfileApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserProfileApi(unittest.TestCase):
    """UserProfileApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_profile_api.UserProfileApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_user_profile_get(self):
        """Test case for user_profile_get

        Obtiene la lista de cuentas contables.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
