# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.category1 import Category1  # noqa: E501
from swagger_client.rest import ApiException


class TestCategory1(unittest.TestCase):
    """Category1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCategory1(self):
        """Test Category1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.category1.Category1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
