# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clients_api import ClientsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientsApi(unittest.TestCase):
    """ClientsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.clients_api.ClientsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clients_add_client(self):
        """Test case for clients_add_client

        Agregar Cliente  # noqa: E501
        """
        pass

    def test_clients_delete_by_id(self):
        """Test case for clients_delete_by_id

        Borrar Cliente  # noqa: E501
        """
        pass

    def test_clients_edit_client(self):
        """Test case for clients_edit_client

        Editar Cliente  # noqa: E501
        """
        pass

    def test_clients_get(self):
        """Test case for clients_get

        Obtiene la lista de clientes.  # noqa: E501
        """
        pass

    def test_clients_get_details(self):
        """Test case for clients_get_details

        Obtiene los detalles de un cliente.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
