# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.web_hooks_api import WebHooksApi  # noqa: E501
from swagger_client.rest import ApiException


class TestWebHooksApi(unittest.TestCase):
    """WebHooksApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.web_hooks_api.WebHooksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_web_hooks_add_web_hook_subscriptions(self):
        """Test case for web_hooks_add_web_hook_subscriptions

        Suscribirse a un WebHook  # noqa: E501
        """
        pass

    def test_web_hooks_delete_web_hook_subscriptio_by_id(self):
        """Test case for web_hooks_delete_web_hook_subscriptio_by_id

        Borrar suscripción a WebHook  # noqa: E501
        """
        pass

    def test_web_hooks_edit_web_hook_subscription(self):
        """Test case for web_hooks_edit_web_hook_subscription

        Editar suscripción a WebHook  # noqa: E501
        """
        pass

    def test_web_hooks_get_web_hook_sample_data(self):
        """Test case for web_hooks_get_web_hook_sample_data

        Obtiene un ejemplo del modelo de datos que envía el WebHook.  # noqa: E501
        """
        pass

    def test_web_hooks_get_web_hook_subscriptions(self):
        """Test case for web_hooks_get_web_hook_subscriptions

        Obtiene la lista de su suscripciones a WebHooks  # noqa: E501
        """
        pass

    def test_web_hooks_get_web_hooks(self):
        """Test case for web_hooks_get_web_hooks

        Obtiene la lista de WebHooks disponibles.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
