# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.accounts_api import AccountsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountsApi(unittest.TestCase):
    """AccountsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.accounts_api.AccountsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounts_add_client(self):
        """Test case for accounts_add_client

        Agregar Cuenta Contable  # noqa: E501
        """
        pass

    def test_accounts_delete_account(self):
        """Test case for accounts_delete_account

        Borrar Cuenta Contable  # noqa: E501
        """
        pass

    def test_accounts_get_account_categories(self):
        """Test case for accounts_get_account_categories

        Obtiene las categorías de cuentas contables.  # noqa: E501
        """
        pass

    def test_accounts_get_price_lists(self):
        """Test case for accounts_get_price_lists

        Obtiene la lista de cuentas contables.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
