# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.location_page import LocationPage  # noqa: E501
from swagger_client.rest import ApiException


class TestLocationPage(unittest.TestCase):
    """LocationPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocationPage(self):
        """Test LocationPage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.location_page.LocationPage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
