# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.select_expand_query_validator import SelectExpandQueryValidator  # noqa: E501
from swagger_client.rest import ApiException


class TestSelectExpandQueryValidator(unittest.TestCase):
    """SelectExpandQueryValidator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSelectExpandQueryValidator(self):
        """Test SelectExpandQueryValidator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.select_expand_query_validator.SelectExpandQueryValidator()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
