# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.order_by_node import OrderByNode  # noqa: E501
from swagger_client.rest import ApiException


class TestOrderByNode(unittest.TestCase):
    """OrderByNode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrderByNode(self):
        """Test OrderByNode"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.order_by_node.OrderByNode()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
