# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class EditProduct(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'code': 'str',
        'title': 'str',
        'cost': 'float',
        'currency_id': 'str',
        'exchange_rate': 'float',
        'sku': 'str',
        'description': 'str',
        'cost_type': 'int',
        'category1_id': 'str',
        'category2_id': 'str',
        'category3_id': 'str',
        'charge_vat': 'bool',
        'number': 'int',
        'pricing_type': 'int',
        'unit': 'str',
        'purchase_type': 'int',
        'ieps_rate': 'float',
        'type': 'int',
        'production_auto': 'bool'
    }

    attribute_map = {
        'id': 'ID',
        'code': 'Code',
        'title': 'Title',
        'cost': 'Cost',
        'currency_id': 'CurrencyID',
        'exchange_rate': 'ExchangeRate',
        'sku': 'SKU',
        'description': 'Description',
        'cost_type': 'CostType',
        'category1_id': 'Category1ID',
        'category2_id': 'Category2ID',
        'category3_id': 'Category3ID',
        'charge_vat': 'ChargeVAT',
        'number': 'Number',
        'pricing_type': 'PricingType',
        'unit': 'Unit',
        'purchase_type': 'PurchaseType',
        'ieps_rate': 'IEPSRate',
        'type': 'Type',
        'production_auto': 'ProductionAuto'
    }

    def __init__(self, id=None, code=None, title=None, cost=None, currency_id=None, exchange_rate=None, sku=None, description=None, cost_type=None, category1_id=None, category2_id=None, category3_id=None, charge_vat=None, number=None, pricing_type=None, unit=None, purchase_type=None, ieps_rate=None, type=None, production_auto=None):  # noqa: E501
        """EditProduct - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._code = None
        self._title = None
        self._cost = None
        self._currency_id = None
        self._exchange_rate = None
        self._sku = None
        self._description = None
        self._cost_type = None
        self._category1_id = None
        self._category2_id = None
        self._category3_id = None
        self._charge_vat = None
        self._number = None
        self._pricing_type = None
        self._unit = None
        self._purchase_type = None
        self._ieps_rate = None
        self._type = None
        self._production_auto = None
        self.discriminator = None

        self.id = id
        self.code = code
        self.title = title
        self.cost = cost
        self.currency_id = currency_id
        if exchange_rate is not None:
            self.exchange_rate = exchange_rate
        if sku is not None:
            self.sku = sku
        if description is not None:
            self.description = description
        if cost_type is not None:
            self.cost_type = cost_type
        if category1_id is not None:
            self.category1_id = category1_id
        if category2_id is not None:
            self.category2_id = category2_id
        if category3_id is not None:
            self.category3_id = category3_id
        if charge_vat is not None:
            self.charge_vat = charge_vat
        if number is not None:
            self.number = number
        if pricing_type is not None:
            self.pricing_type = pricing_type
        if unit is not None:
            self.unit = unit
        if purchase_type is not None:
            self.purchase_type = purchase_type
        if ieps_rate is not None:
            self.ieps_rate = ieps_rate
        if type is not None:
            self.type = type
        if production_auto is not None:
            self.production_auto = production_auto

    @property
    def id(self):
        """Gets the id of this EditProduct.  # noqa: E501


        :return: The id of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EditProduct.


        :param id: The id of this EditProduct.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def code(self):
        """Gets the code of this EditProduct.  # noqa: E501


        :return: The code of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this EditProduct.


        :param code: The code of this EditProduct.  # noqa: E501
        :type: str
        """
        if code is None:
            raise ValueError("Invalid value for `code`, must not be `None`")  # noqa: E501

        self._code = code

    @property
    def title(self):
        """Gets the title of this EditProduct.  # noqa: E501


        :return: The title of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this EditProduct.


        :param title: The title of this EditProduct.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def cost(self):
        """Gets the cost of this EditProduct.  # noqa: E501


        :return: The cost of this EditProduct.  # noqa: E501
        :rtype: float
        """
        return self._cost

    @cost.setter
    def cost(self, cost):
        """Sets the cost of this EditProduct.


        :param cost: The cost of this EditProduct.  # noqa: E501
        :type: float
        """
        if cost is None:
            raise ValueError("Invalid value for `cost`, must not be `None`")  # noqa: E501

        self._cost = cost

    @property
    def currency_id(self):
        """Gets the currency_id of this EditProduct.  # noqa: E501


        :return: The currency_id of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id):
        """Sets the currency_id of this EditProduct.


        :param currency_id: The currency_id of this EditProduct.  # noqa: E501
        :type: str
        """
        if currency_id is None:
            raise ValueError("Invalid value for `currency_id`, must not be `None`")  # noqa: E501

        self._currency_id = currency_id

    @property
    def exchange_rate(self):
        """Gets the exchange_rate of this EditProduct.  # noqa: E501


        :return: The exchange_rate of this EditProduct.  # noqa: E501
        :rtype: float
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate):
        """Sets the exchange_rate of this EditProduct.


        :param exchange_rate: The exchange_rate of this EditProduct.  # noqa: E501
        :type: float
        """

        self._exchange_rate = exchange_rate

    @property
    def sku(self):
        """Gets the sku of this EditProduct.  # noqa: E501


        :return: The sku of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._sku

    @sku.setter
    def sku(self, sku):
        """Sets the sku of this EditProduct.


        :param sku: The sku of this EditProduct.  # noqa: E501
        :type: str
        """

        self._sku = sku

    @property
    def description(self):
        """Gets the description of this EditProduct.  # noqa: E501


        :return: The description of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this EditProduct.


        :param description: The description of this EditProduct.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def cost_type(self):
        """Gets the cost_type of this EditProduct.  # noqa: E501


        :return: The cost_type of this EditProduct.  # noqa: E501
        :rtype: int
        """
        return self._cost_type

    @cost_type.setter
    def cost_type(self, cost_type):
        """Sets the cost_type of this EditProduct.


        :param cost_type: The cost_type of this EditProduct.  # noqa: E501
        :type: int
        """

        self._cost_type = cost_type

    @property
    def category1_id(self):
        """Gets the category1_id of this EditProduct.  # noqa: E501


        :return: The category1_id of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._category1_id

    @category1_id.setter
    def category1_id(self, category1_id):
        """Sets the category1_id of this EditProduct.


        :param category1_id: The category1_id of this EditProduct.  # noqa: E501
        :type: str
        """

        self._category1_id = category1_id

    @property
    def category2_id(self):
        """Gets the category2_id of this EditProduct.  # noqa: E501


        :return: The category2_id of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._category2_id

    @category2_id.setter
    def category2_id(self, category2_id):
        """Sets the category2_id of this EditProduct.


        :param category2_id: The category2_id of this EditProduct.  # noqa: E501
        :type: str
        """

        self._category2_id = category2_id

    @property
    def category3_id(self):
        """Gets the category3_id of this EditProduct.  # noqa: E501


        :return: The category3_id of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._category3_id

    @category3_id.setter
    def category3_id(self, category3_id):
        """Sets the category3_id of this EditProduct.


        :param category3_id: The category3_id of this EditProduct.  # noqa: E501
        :type: str
        """

        self._category3_id = category3_id

    @property
    def charge_vat(self):
        """Gets the charge_vat of this EditProduct.  # noqa: E501


        :return: The charge_vat of this EditProduct.  # noqa: E501
        :rtype: bool
        """
        return self._charge_vat

    @charge_vat.setter
    def charge_vat(self, charge_vat):
        """Sets the charge_vat of this EditProduct.


        :param charge_vat: The charge_vat of this EditProduct.  # noqa: E501
        :type: bool
        """

        self._charge_vat = charge_vat

    @property
    def number(self):
        """Gets the number of this EditProduct.  # noqa: E501


        :return: The number of this EditProduct.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this EditProduct.


        :param number: The number of this EditProduct.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def pricing_type(self):
        """Gets the pricing_type of this EditProduct.  # noqa: E501


        :return: The pricing_type of this EditProduct.  # noqa: E501
        :rtype: int
        """
        return self._pricing_type

    @pricing_type.setter
    def pricing_type(self, pricing_type):
        """Sets the pricing_type of this EditProduct.


        :param pricing_type: The pricing_type of this EditProduct.  # noqa: E501
        :type: int
        """

        self._pricing_type = pricing_type

    @property
    def unit(self):
        """Gets the unit of this EditProduct.  # noqa: E501


        :return: The unit of this EditProduct.  # noqa: E501
        :rtype: str
        """
        return self._unit

    @unit.setter
    def unit(self, unit):
        """Sets the unit of this EditProduct.


        :param unit: The unit of this EditProduct.  # noqa: E501
        :type: str
        """

        self._unit = unit

    @property
    def purchase_type(self):
        """Gets the purchase_type of this EditProduct.  # noqa: E501


        :return: The purchase_type of this EditProduct.  # noqa: E501
        :rtype: int
        """
        return self._purchase_type

    @purchase_type.setter
    def purchase_type(self, purchase_type):
        """Sets the purchase_type of this EditProduct.


        :param purchase_type: The purchase_type of this EditProduct.  # noqa: E501
        :type: int
        """

        self._purchase_type = purchase_type

    @property
    def ieps_rate(self):
        """Gets the ieps_rate of this EditProduct.  # noqa: E501


        :return: The ieps_rate of this EditProduct.  # noqa: E501
        :rtype: float
        """
        return self._ieps_rate

    @ieps_rate.setter
    def ieps_rate(self, ieps_rate):
        """Sets the ieps_rate of this EditProduct.


        :param ieps_rate: The ieps_rate of this EditProduct.  # noqa: E501
        :type: float
        """

        self._ieps_rate = ieps_rate

    @property
    def type(self):
        """Gets the type of this EditProduct.  # noqa: E501


        :return: The type of this EditProduct.  # noqa: E501
        :rtype: int
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this EditProduct.


        :param type: The type of this EditProduct.  # noqa: E501
        :type: int
        """

        self._type = type

    @property
    def production_auto(self):
        """Gets the production_auto of this EditProduct.  # noqa: E501


        :return: The production_auto of this EditProduct.  # noqa: E501
        :rtype: bool
        """
        return self._production_auto

    @production_auto.setter
    def production_auto(self, production_auto):
        """Sets the production_auto of this EditProduct.


        :param production_auto: The production_auto of this EditProduct.  # noqa: E501
        :type: bool
        """

        self._production_auto = production_auto

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EditProduct):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
