# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.o_data_query_context import ODataQueryContext  # noqa: F401,E501


class InlineCountQueryOption(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'context': 'ODataQueryContext',
        'raw_value': 'str',
        'value': 'str'
    }

    attribute_map = {
        'context': 'Context',
        'raw_value': 'RawValue',
        'value': 'Value'
    }

    def __init__(self, context=None, raw_value=None, value=None):  # noqa: E501
        """InlineCountQueryOption - a model defined in Swagger"""  # noqa: E501

        self._context = None
        self._raw_value = None
        self._value = None
        self.discriminator = None

        if context is not None:
            self.context = context
        if raw_value is not None:
            self.raw_value = raw_value
        if value is not None:
            self.value = value

    @property
    def context(self):
        """Gets the context of this InlineCountQueryOption.  # noqa: E501


        :return: The context of this InlineCountQueryOption.  # noqa: E501
        :rtype: ODataQueryContext
        """
        return self._context

    @context.setter
    def context(self, context):
        """Sets the context of this InlineCountQueryOption.


        :param context: The context of this InlineCountQueryOption.  # noqa: E501
        :type: ODataQueryContext
        """

        self._context = context

    @property
    def raw_value(self):
        """Gets the raw_value of this InlineCountQueryOption.  # noqa: E501


        :return: The raw_value of this InlineCountQueryOption.  # noqa: E501
        :rtype: str
        """
        return self._raw_value

    @raw_value.setter
    def raw_value(self, raw_value):
        """Sets the raw_value of this InlineCountQueryOption.


        :param raw_value: The raw_value of this InlineCountQueryOption.  # noqa: E501
        :type: str
        """

        self._raw_value = raw_value

    @property
    def value(self):
        """Gets the value of this InlineCountQueryOption.  # noqa: E501


        :return: The value of this InlineCountQueryOption.  # noqa: E501
        :rtype: str
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this InlineCountQueryOption.


        :param value: The value of this InlineCountQueryOption.  # noqa: E501
        :type: str
        """
        allowed_values = ["None", "AllPages"]  # noqa: E501
        if value not in allowed_values:
            raise ValueError(
                "Invalid value for `value` ({0}), must be one of {1}"  # noqa: E501
                .format(value, allowed_values)
            )

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineCountQueryOption):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
