# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.invoice_details_product import InvoiceDetailsProduct  # noqa: F401,E501
from swagger_client.models.invoice_details_service import InvoiceDetailsService  # noqa: F401,E501


class InvoiceDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'uuid': 'str',
        'series': 'str',
        'number': 'int',
        'client_id': 'str',
        'client_name': 'str',
        'payment_terms': 'int',
        'status': 'str',
        'status_code': 'int',
        'client_phone_number': 'str',
        'client_contact': 'str',
        'rfc': 'str',
        'created_by_id': 'str',
        'created_by_name': 'str',
        'creation_date': 'datetime',
        'application_date': 'datetime',
        'price_list_id': 'str',
        'price_list_name': 'str',
        'location_id': 'str',
        'location_name': 'str',
        'warehouse_id': 'str',
        'warehouse_name': 'str',
        'cfdi_payment_method': 'str',
        'cfdi_payment_term': 'str',
        'cfdi_account_number': 'str',
        'currency_name': 'str',
        'exchange_rate': 'float',
        'purchase_order': 'str',
        'fiscal_id': 'str',
        'address': 'str',
        'comments': 'str',
        'subtotal': 'float',
        'discount': 'float',
        'vat': 'float',
        'ieps': 'float',
        'vat_ret': 'float',
        'isr_ret': 'float',
        'payments': 'float',
        'credit_notes': 'float',
        'products': 'list[InvoiceDetailsProduct]',
        'services': 'list[InvoiceDetailsService]'
    }

    attribute_map = {
        'id': 'ID',
        'uuid': 'UUID',
        'series': 'Series',
        'number': 'Number',
        'client_id': 'ClientID',
        'client_name': 'ClientName',
        'payment_terms': 'PaymentTerms',
        'status': 'Status',
        'status_code': 'StatusCode',
        'client_phone_number': 'ClientPhoneNumber',
        'client_contact': 'ClientContact',
        'rfc': 'RFC',
        'created_by_id': 'CreatedByID',
        'created_by_name': 'CreatedByName',
        'creation_date': 'CreationDate',
        'application_date': 'ApplicationDate',
        'price_list_id': 'PriceListID',
        'price_list_name': 'PriceListName',
        'location_id': 'LocationID',
        'location_name': 'LocationName',
        'warehouse_id': 'WarehouseID',
        'warehouse_name': 'WarehouseName',
        'cfdi_payment_method': 'CFDIPaymentMethod',
        'cfdi_payment_term': 'CFDIPaymentTerm',
        'cfdi_account_number': 'CFDIAccountNumber',
        'currency_name': 'CurrencyName',
        'exchange_rate': 'ExchangeRate',
        'purchase_order': 'PurchaseOrder',
        'fiscal_id': 'FiscalID',
        'address': 'Address',
        'comments': 'Comments',
        'subtotal': 'Subtotal',
        'discount': 'Discount',
        'vat': 'VAT',
        'ieps': 'IEPS',
        'vat_ret': 'VATRet',
        'isr_ret': 'ISRRet',
        'payments': 'Payments',
        'credit_notes': 'CreditNotes',
        'products': 'Products',
        'services': 'Services'
    }

    def __init__(self, id=None, uuid=None, series=None, number=None, client_id=None, client_name=None, payment_terms=None, status=None, status_code=None, client_phone_number=None, client_contact=None, rfc=None, created_by_id=None, created_by_name=None, creation_date=None, application_date=None, price_list_id=None, price_list_name=None, location_id=None, location_name=None, warehouse_id=None, warehouse_name=None, cfdi_payment_method=None, cfdi_payment_term=None, cfdi_account_number=None, currency_name=None, exchange_rate=None, purchase_order=None, fiscal_id=None, address=None, comments=None, subtotal=None, discount=None, vat=None, ieps=None, vat_ret=None, isr_ret=None, payments=None, credit_notes=None, products=None, services=None):  # noqa: E501
        """InvoiceDetails - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._uuid = None
        self._series = None
        self._number = None
        self._client_id = None
        self._client_name = None
        self._payment_terms = None
        self._status = None
        self._status_code = None
        self._client_phone_number = None
        self._client_contact = None
        self._rfc = None
        self._created_by_id = None
        self._created_by_name = None
        self._creation_date = None
        self._application_date = None
        self._price_list_id = None
        self._price_list_name = None
        self._location_id = None
        self._location_name = None
        self._warehouse_id = None
        self._warehouse_name = None
        self._cfdi_payment_method = None
        self._cfdi_payment_term = None
        self._cfdi_account_number = None
        self._currency_name = None
        self._exchange_rate = None
        self._purchase_order = None
        self._fiscal_id = None
        self._address = None
        self._comments = None
        self._subtotal = None
        self._discount = None
        self._vat = None
        self._ieps = None
        self._vat_ret = None
        self._isr_ret = None
        self._payments = None
        self._credit_notes = None
        self._products = None
        self._services = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if uuid is not None:
            self.uuid = uuid
        if series is not None:
            self.series = series
        if number is not None:
            self.number = number
        if client_id is not None:
            self.client_id = client_id
        if client_name is not None:
            self.client_name = client_name
        if payment_terms is not None:
            self.payment_terms = payment_terms
        if status is not None:
            self.status = status
        if status_code is not None:
            self.status_code = status_code
        if client_phone_number is not None:
            self.client_phone_number = client_phone_number
        if client_contact is not None:
            self.client_contact = client_contact
        if rfc is not None:
            self.rfc = rfc
        if created_by_id is not None:
            self.created_by_id = created_by_id
        if created_by_name is not None:
            self.created_by_name = created_by_name
        if creation_date is not None:
            self.creation_date = creation_date
        if application_date is not None:
            self.application_date = application_date
        if price_list_id is not None:
            self.price_list_id = price_list_id
        if price_list_name is not None:
            self.price_list_name = price_list_name
        if location_id is not None:
            self.location_id = location_id
        if location_name is not None:
            self.location_name = location_name
        if warehouse_id is not None:
            self.warehouse_id = warehouse_id
        if warehouse_name is not None:
            self.warehouse_name = warehouse_name
        if cfdi_payment_method is not None:
            self.cfdi_payment_method = cfdi_payment_method
        if cfdi_payment_term is not None:
            self.cfdi_payment_term = cfdi_payment_term
        if cfdi_account_number is not None:
            self.cfdi_account_number = cfdi_account_number
        if currency_name is not None:
            self.currency_name = currency_name
        if exchange_rate is not None:
            self.exchange_rate = exchange_rate
        if purchase_order is not None:
            self.purchase_order = purchase_order
        if fiscal_id is not None:
            self.fiscal_id = fiscal_id
        if address is not None:
            self.address = address
        if comments is not None:
            self.comments = comments
        if subtotal is not None:
            self.subtotal = subtotal
        if discount is not None:
            self.discount = discount
        if vat is not None:
            self.vat = vat
        if ieps is not None:
            self.ieps = ieps
        if vat_ret is not None:
            self.vat_ret = vat_ret
        if isr_ret is not None:
            self.isr_ret = isr_ret
        if payments is not None:
            self.payments = payments
        if credit_notes is not None:
            self.credit_notes = credit_notes
        if products is not None:
            self.products = products
        if services is not None:
            self.services = services

    @property
    def id(self):
        """Gets the id of this InvoiceDetails.  # noqa: E501


        :return: The id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InvoiceDetails.


        :param id: The id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def uuid(self):
        """Gets the uuid of this InvoiceDetails.  # noqa: E501


        :return: The uuid of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this InvoiceDetails.


        :param uuid: The uuid of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def series(self):
        """Gets the series of this InvoiceDetails.  # noqa: E501


        :return: The series of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._series

    @series.setter
    def series(self, series):
        """Sets the series of this InvoiceDetails.


        :param series: The series of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._series = series

    @property
    def number(self):
        """Gets the number of this InvoiceDetails.  # noqa: E501


        :return: The number of this InvoiceDetails.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this InvoiceDetails.


        :param number: The number of this InvoiceDetails.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def client_id(self):
        """Gets the client_id of this InvoiceDetails.  # noqa: E501


        :return: The client_id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this InvoiceDetails.


        :param client_id: The client_id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def client_name(self):
        """Gets the client_name of this InvoiceDetails.  # noqa: E501


        :return: The client_name of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._client_name

    @client_name.setter
    def client_name(self, client_name):
        """Sets the client_name of this InvoiceDetails.


        :param client_name: The client_name of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._client_name = client_name

    @property
    def payment_terms(self):
        """Gets the payment_terms of this InvoiceDetails.  # noqa: E501


        :return: The payment_terms of this InvoiceDetails.  # noqa: E501
        :rtype: int
        """
        return self._payment_terms

    @payment_terms.setter
    def payment_terms(self, payment_terms):
        """Sets the payment_terms of this InvoiceDetails.


        :param payment_terms: The payment_terms of this InvoiceDetails.  # noqa: E501
        :type: int
        """

        self._payment_terms = payment_terms

    @property
    def status(self):
        """Gets the status of this InvoiceDetails.  # noqa: E501


        :return: The status of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this InvoiceDetails.


        :param status: The status of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def status_code(self):
        """Gets the status_code of this InvoiceDetails.  # noqa: E501


        :return: The status_code of this InvoiceDetails.  # noqa: E501
        :rtype: int
        """
        return self._status_code

    @status_code.setter
    def status_code(self, status_code):
        """Sets the status_code of this InvoiceDetails.


        :param status_code: The status_code of this InvoiceDetails.  # noqa: E501
        :type: int
        """

        self._status_code = status_code

    @property
    def client_phone_number(self):
        """Gets the client_phone_number of this InvoiceDetails.  # noqa: E501


        :return: The client_phone_number of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._client_phone_number

    @client_phone_number.setter
    def client_phone_number(self, client_phone_number):
        """Sets the client_phone_number of this InvoiceDetails.


        :param client_phone_number: The client_phone_number of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._client_phone_number = client_phone_number

    @property
    def client_contact(self):
        """Gets the client_contact of this InvoiceDetails.  # noqa: E501


        :return: The client_contact of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._client_contact

    @client_contact.setter
    def client_contact(self, client_contact):
        """Sets the client_contact of this InvoiceDetails.


        :param client_contact: The client_contact of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._client_contact = client_contact

    @property
    def rfc(self):
        """Gets the rfc of this InvoiceDetails.  # noqa: E501


        :return: The rfc of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._rfc

    @rfc.setter
    def rfc(self, rfc):
        """Sets the rfc of this InvoiceDetails.


        :param rfc: The rfc of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._rfc = rfc

    @property
    def created_by_id(self):
        """Gets the created_by_id of this InvoiceDetails.  # noqa: E501


        :return: The created_by_id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._created_by_id

    @created_by_id.setter
    def created_by_id(self, created_by_id):
        """Sets the created_by_id of this InvoiceDetails.


        :param created_by_id: The created_by_id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._created_by_id = created_by_id

    @property
    def created_by_name(self):
        """Gets the created_by_name of this InvoiceDetails.  # noqa: E501


        :return: The created_by_name of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._created_by_name

    @created_by_name.setter
    def created_by_name(self, created_by_name):
        """Sets the created_by_name of this InvoiceDetails.


        :param created_by_name: The created_by_name of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._created_by_name = created_by_name

    @property
    def creation_date(self):
        """Gets the creation_date of this InvoiceDetails.  # noqa: E501


        :return: The creation_date of this InvoiceDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_date

    @creation_date.setter
    def creation_date(self, creation_date):
        """Sets the creation_date of this InvoiceDetails.


        :param creation_date: The creation_date of this InvoiceDetails.  # noqa: E501
        :type: datetime
        """

        self._creation_date = creation_date

    @property
    def application_date(self):
        """Gets the application_date of this InvoiceDetails.  # noqa: E501


        :return: The application_date of this InvoiceDetails.  # noqa: E501
        :rtype: datetime
        """
        return self._application_date

    @application_date.setter
    def application_date(self, application_date):
        """Sets the application_date of this InvoiceDetails.


        :param application_date: The application_date of this InvoiceDetails.  # noqa: E501
        :type: datetime
        """

        self._application_date = application_date

    @property
    def price_list_id(self):
        """Gets the price_list_id of this InvoiceDetails.  # noqa: E501


        :return: The price_list_id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._price_list_id

    @price_list_id.setter
    def price_list_id(self, price_list_id):
        """Sets the price_list_id of this InvoiceDetails.


        :param price_list_id: The price_list_id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._price_list_id = price_list_id

    @property
    def price_list_name(self):
        """Gets the price_list_name of this InvoiceDetails.  # noqa: E501


        :return: The price_list_name of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._price_list_name

    @price_list_name.setter
    def price_list_name(self, price_list_name):
        """Sets the price_list_name of this InvoiceDetails.


        :param price_list_name: The price_list_name of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._price_list_name = price_list_name

    @property
    def location_id(self):
        """Gets the location_id of this InvoiceDetails.  # noqa: E501


        :return: The location_id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this InvoiceDetails.


        :param location_id: The location_id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._location_id = location_id

    @property
    def location_name(self):
        """Gets the location_name of this InvoiceDetails.  # noqa: E501


        :return: The location_name of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._location_name

    @location_name.setter
    def location_name(self, location_name):
        """Sets the location_name of this InvoiceDetails.


        :param location_name: The location_name of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._location_name = location_name

    @property
    def warehouse_id(self):
        """Gets the warehouse_id of this InvoiceDetails.  # noqa: E501


        :return: The warehouse_id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._warehouse_id

    @warehouse_id.setter
    def warehouse_id(self, warehouse_id):
        """Sets the warehouse_id of this InvoiceDetails.


        :param warehouse_id: The warehouse_id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._warehouse_id = warehouse_id

    @property
    def warehouse_name(self):
        """Gets the warehouse_name of this InvoiceDetails.  # noqa: E501


        :return: The warehouse_name of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._warehouse_name

    @warehouse_name.setter
    def warehouse_name(self, warehouse_name):
        """Sets the warehouse_name of this InvoiceDetails.


        :param warehouse_name: The warehouse_name of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._warehouse_name = warehouse_name

    @property
    def cfdi_payment_method(self):
        """Gets the cfdi_payment_method of this InvoiceDetails.  # noqa: E501


        :return: The cfdi_payment_method of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._cfdi_payment_method

    @cfdi_payment_method.setter
    def cfdi_payment_method(self, cfdi_payment_method):
        """Sets the cfdi_payment_method of this InvoiceDetails.


        :param cfdi_payment_method: The cfdi_payment_method of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._cfdi_payment_method = cfdi_payment_method

    @property
    def cfdi_payment_term(self):
        """Gets the cfdi_payment_term of this InvoiceDetails.  # noqa: E501


        :return: The cfdi_payment_term of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._cfdi_payment_term

    @cfdi_payment_term.setter
    def cfdi_payment_term(self, cfdi_payment_term):
        """Sets the cfdi_payment_term of this InvoiceDetails.


        :param cfdi_payment_term: The cfdi_payment_term of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._cfdi_payment_term = cfdi_payment_term

    @property
    def cfdi_account_number(self):
        """Gets the cfdi_account_number of this InvoiceDetails.  # noqa: E501


        :return: The cfdi_account_number of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._cfdi_account_number

    @cfdi_account_number.setter
    def cfdi_account_number(self, cfdi_account_number):
        """Sets the cfdi_account_number of this InvoiceDetails.


        :param cfdi_account_number: The cfdi_account_number of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._cfdi_account_number = cfdi_account_number

    @property
    def currency_name(self):
        """Gets the currency_name of this InvoiceDetails.  # noqa: E501


        :return: The currency_name of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._currency_name

    @currency_name.setter
    def currency_name(self, currency_name):
        """Sets the currency_name of this InvoiceDetails.


        :param currency_name: The currency_name of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._currency_name = currency_name

    @property
    def exchange_rate(self):
        """Gets the exchange_rate of this InvoiceDetails.  # noqa: E501


        :return: The exchange_rate of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate):
        """Sets the exchange_rate of this InvoiceDetails.


        :param exchange_rate: The exchange_rate of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._exchange_rate = exchange_rate

    @property
    def purchase_order(self):
        """Gets the purchase_order of this InvoiceDetails.  # noqa: E501


        :return: The purchase_order of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._purchase_order

    @purchase_order.setter
    def purchase_order(self, purchase_order):
        """Sets the purchase_order of this InvoiceDetails.


        :param purchase_order: The purchase_order of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._purchase_order = purchase_order

    @property
    def fiscal_id(self):
        """Gets the fiscal_id of this InvoiceDetails.  # noqa: E501


        :return: The fiscal_id of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._fiscal_id

    @fiscal_id.setter
    def fiscal_id(self, fiscal_id):
        """Sets the fiscal_id of this InvoiceDetails.


        :param fiscal_id: The fiscal_id of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._fiscal_id = fiscal_id

    @property
    def address(self):
        """Gets the address of this InvoiceDetails.  # noqa: E501


        :return: The address of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._address

    @address.setter
    def address(self, address):
        """Sets the address of this InvoiceDetails.


        :param address: The address of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._address = address

    @property
    def comments(self):
        """Gets the comments of this InvoiceDetails.  # noqa: E501


        :return: The comments of this InvoiceDetails.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this InvoiceDetails.


        :param comments: The comments of this InvoiceDetails.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def subtotal(self):
        """Gets the subtotal of this InvoiceDetails.  # noqa: E501


        :return: The subtotal of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._subtotal

    @subtotal.setter
    def subtotal(self, subtotal):
        """Sets the subtotal of this InvoiceDetails.


        :param subtotal: The subtotal of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._subtotal = subtotal

    @property
    def discount(self):
        """Gets the discount of this InvoiceDetails.  # noqa: E501


        :return: The discount of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._discount

    @discount.setter
    def discount(self, discount):
        """Sets the discount of this InvoiceDetails.


        :param discount: The discount of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._discount = discount

    @property
    def vat(self):
        """Gets the vat of this InvoiceDetails.  # noqa: E501


        :return: The vat of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._vat

    @vat.setter
    def vat(self, vat):
        """Sets the vat of this InvoiceDetails.


        :param vat: The vat of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._vat = vat

    @property
    def ieps(self):
        """Gets the ieps of this InvoiceDetails.  # noqa: E501


        :return: The ieps of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._ieps

    @ieps.setter
    def ieps(self, ieps):
        """Sets the ieps of this InvoiceDetails.


        :param ieps: The ieps of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._ieps = ieps

    @property
    def vat_ret(self):
        """Gets the vat_ret of this InvoiceDetails.  # noqa: E501


        :return: The vat_ret of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._vat_ret

    @vat_ret.setter
    def vat_ret(self, vat_ret):
        """Sets the vat_ret of this InvoiceDetails.


        :param vat_ret: The vat_ret of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._vat_ret = vat_ret

    @property
    def isr_ret(self):
        """Gets the isr_ret of this InvoiceDetails.  # noqa: E501


        :return: The isr_ret of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._isr_ret

    @isr_ret.setter
    def isr_ret(self, isr_ret):
        """Sets the isr_ret of this InvoiceDetails.


        :param isr_ret: The isr_ret of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._isr_ret = isr_ret

    @property
    def payments(self):
        """Gets the payments of this InvoiceDetails.  # noqa: E501


        :return: The payments of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._payments

    @payments.setter
    def payments(self, payments):
        """Sets the payments of this InvoiceDetails.


        :param payments: The payments of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._payments = payments

    @property
    def credit_notes(self):
        """Gets the credit_notes of this InvoiceDetails.  # noqa: E501


        :return: The credit_notes of this InvoiceDetails.  # noqa: E501
        :rtype: float
        """
        return self._credit_notes

    @credit_notes.setter
    def credit_notes(self, credit_notes):
        """Sets the credit_notes of this InvoiceDetails.


        :param credit_notes: The credit_notes of this InvoiceDetails.  # noqa: E501
        :type: float
        """

        self._credit_notes = credit_notes

    @property
    def products(self):
        """Gets the products of this InvoiceDetails.  # noqa: E501


        :return: The products of this InvoiceDetails.  # noqa: E501
        :rtype: list[InvoiceDetailsProduct]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this InvoiceDetails.


        :param products: The products of this InvoiceDetails.  # noqa: E501
        :type: list[InvoiceDetailsProduct]
        """

        self._products = products

    @property
    def services(self):
        """Gets the services of this InvoiceDetails.  # noqa: E501


        :return: The services of this InvoiceDetails.  # noqa: E501
        :rtype: list[InvoiceDetailsService]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this InvoiceDetails.


        :param services: The services of this InvoiceDetails.  # noqa: E501
        :type: list[InvoiceDetailsService]
        """

        self._services = services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoiceDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
