# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class NewOrderService(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'title': 'str',
        'price': 'float',
        'vat': 'float',
        'qty': 'float',
        'comments': 'str',
        'vat_exempt': 'bool',
        'index_number': 'int',
        'variable_concept': 'bool',
        'order_item_id': 'str'
    }

    attribute_map = {
        'id': 'ID',
        'title': 'Title',
        'price': 'Price',
        'vat': 'VAT',
        'qty': 'Qty',
        'comments': 'Comments',
        'vat_exempt': 'VATExempt',
        'index_number': 'IndexNumber',
        'variable_concept': 'VariableConcept',
        'order_item_id': 'OrderItemID'
    }

    def __init__(self, id=None, title=None, price=None, vat=None, qty=None, comments=None, vat_exempt=None, index_number=None, variable_concept=None, order_item_id=None):  # noqa: E501
        """NewOrderService - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._title = None
        self._price = None
        self._vat = None
        self._qty = None
        self._comments = None
        self._vat_exempt = None
        self._index_number = None
        self._variable_concept = None
        self._order_item_id = None
        self.discriminator = None

        self.id = id
        self.title = title
        self.price = price
        if vat is not None:
            self.vat = vat
        self.qty = qty
        if comments is not None:
            self.comments = comments
        if vat_exempt is not None:
            self.vat_exempt = vat_exempt
        if index_number is not None:
            self.index_number = index_number
        if variable_concept is not None:
            self.variable_concept = variable_concept
        if order_item_id is not None:
            self.order_item_id = order_item_id

    @property
    def id(self):
        """Gets the id of this NewOrderService.  # noqa: E501


        :return: The id of this NewOrderService.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this NewOrderService.


        :param id: The id of this NewOrderService.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self):
        """Gets the title of this NewOrderService.  # noqa: E501


        :return: The title of this NewOrderService.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this NewOrderService.


        :param title: The title of this NewOrderService.  # noqa: E501
        :type: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def price(self):
        """Gets the price of this NewOrderService.  # noqa: E501


        :return: The price of this NewOrderService.  # noqa: E501
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """Sets the price of this NewOrderService.


        :param price: The price of this NewOrderService.  # noqa: E501
        :type: float
        """
        if price is None:
            raise ValueError("Invalid value for `price`, must not be `None`")  # noqa: E501

        self._price = price

    @property
    def vat(self):
        """Gets the vat of this NewOrderService.  # noqa: E501


        :return: The vat of this NewOrderService.  # noqa: E501
        :rtype: float
        """
        return self._vat

    @vat.setter
    def vat(self, vat):
        """Sets the vat of this NewOrderService.


        :param vat: The vat of this NewOrderService.  # noqa: E501
        :type: float
        """

        self._vat = vat

    @property
    def qty(self):
        """Gets the qty of this NewOrderService.  # noqa: E501


        :return: The qty of this NewOrderService.  # noqa: E501
        :rtype: float
        """
        return self._qty

    @qty.setter
    def qty(self, qty):
        """Sets the qty of this NewOrderService.


        :param qty: The qty of this NewOrderService.  # noqa: E501
        :type: float
        """
        if qty is None:
            raise ValueError("Invalid value for `qty`, must not be `None`")  # noqa: E501

        self._qty = qty

    @property
    def comments(self):
        """Gets the comments of this NewOrderService.  # noqa: E501


        :return: The comments of this NewOrderService.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this NewOrderService.


        :param comments: The comments of this NewOrderService.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def vat_exempt(self):
        """Gets the vat_exempt of this NewOrderService.  # noqa: E501


        :return: The vat_exempt of this NewOrderService.  # noqa: E501
        :rtype: bool
        """
        return self._vat_exempt

    @vat_exempt.setter
    def vat_exempt(self, vat_exempt):
        """Sets the vat_exempt of this NewOrderService.


        :param vat_exempt: The vat_exempt of this NewOrderService.  # noqa: E501
        :type: bool
        """

        self._vat_exempt = vat_exempt

    @property
    def index_number(self):
        """Gets the index_number of this NewOrderService.  # noqa: E501


        :return: The index_number of this NewOrderService.  # noqa: E501
        :rtype: int
        """
        return self._index_number

    @index_number.setter
    def index_number(self, index_number):
        """Sets the index_number of this NewOrderService.


        :param index_number: The index_number of this NewOrderService.  # noqa: E501
        :type: int
        """

        self._index_number = index_number

    @property
    def variable_concept(self):
        """Gets the variable_concept of this NewOrderService.  # noqa: E501


        :return: The variable_concept of this NewOrderService.  # noqa: E501
        :rtype: bool
        """
        return self._variable_concept

    @variable_concept.setter
    def variable_concept(self, variable_concept):
        """Sets the variable_concept of this NewOrderService.


        :param variable_concept: The variable_concept of this NewOrderService.  # noqa: E501
        :type: bool
        """

        self._variable_concept = variable_concept

    @property
    def order_item_id(self):
        """Gets the order_item_id of this NewOrderService.  # noqa: E501


        :return: The order_item_id of this NewOrderService.  # noqa: E501
        :rtype: str
        """
        return self._order_item_id

    @order_item_id.setter
    def order_item_id(self, order_item_id):
        """Sets the order_item_id of this NewOrderService.


        :param order_item_id: The order_item_id of this NewOrderService.  # noqa: E501
        :type: str
        """

        self._order_item_id = order_item_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewOrderService):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
