# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.new_invoice_payment import NewInvoicePayment  # noqa: F401,E501
from swagger_client.models.new_invoice_product import NewInvoiceProduct  # noqa: F401,E501
from swagger_client.models.new_invoice_service import NewInvoiceService  # noqa: F401,E501


class NewInvoice(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'currency_id': 'str',
        'client_id': 'str',
        'location_id': 'str',
        'warehouse_id': 'str',
        'cfdi_use': 'int',
        'invoice_date': 'datetime',
        'price_list_id': 'str',
        'exchange_rate': 'float',
        'isr_ret_rate': 'float',
        'vat_ret_rate': 'float',
        'comments': 'str',
        'vat_rate': 'float',
        'discount_type': 'int',
        'discount_amount': 'float',
        'products': 'list[NewInvoiceProduct]',
        'services': 'list[NewInvoiceService]',
        'emails': 'list[str]',
        'purchase_order': 'str',
        'credit_days': 'int',
        'is_fiscal_invoice': 'bool',
        'show_ieps': 'bool',
        'number': 'int',
        'account': 'str',
        'payments': 'list[NewInvoicePayment]',
        'serie': 'str'
    }

    attribute_map = {
        'currency_id': 'CurrencyID',
        'client_id': 'ClientID',
        'location_id': 'LocationID',
        'warehouse_id': 'WarehouseID',
        'cfdi_use': 'CFDIUse',
        'invoice_date': 'InvoiceDate',
        'price_list_id': 'PriceListID',
        'exchange_rate': 'ExchangeRate',
        'isr_ret_rate': 'ISRRetRate',
        'vat_ret_rate': 'VATRetRate',
        'comments': 'Comments',
        'vat_rate': 'VATRate',
        'discount_type': 'DiscountType',
        'discount_amount': 'DiscountAmount',
        'products': 'Products',
        'services': 'Services',
        'emails': 'Emails',
        'purchase_order': 'PurchaseOrder',
        'credit_days': 'CreditDays',
        'is_fiscal_invoice': 'IsFiscalInvoice',
        'show_ieps': 'ShowIEPS',
        'number': 'Number',
        'account': 'Account',
        'payments': 'Payments',
        'serie': 'Serie'
    }

    def __init__(self, currency_id=None, client_id=None, location_id=None, warehouse_id=None, cfdi_use=None, invoice_date=None, price_list_id=None, exchange_rate=None, isr_ret_rate=None, vat_ret_rate=None, comments=None, vat_rate=None, discount_type=None, discount_amount=None, products=None, services=None, emails=None, purchase_order=None, credit_days=None, is_fiscal_invoice=None, show_ieps=None, number=None, account=None, payments=None, serie=None):  # noqa: E501
        """NewInvoice - a model defined in Swagger"""  # noqa: E501

        self._currency_id = None
        self._client_id = None
        self._location_id = None
        self._warehouse_id = None
        self._cfdi_use = None
        self._invoice_date = None
        self._price_list_id = None
        self._exchange_rate = None
        self._isr_ret_rate = None
        self._vat_ret_rate = None
        self._comments = None
        self._vat_rate = None
        self._discount_type = None
        self._discount_amount = None
        self._products = None
        self._services = None
        self._emails = None
        self._purchase_order = None
        self._credit_days = None
        self._is_fiscal_invoice = None
        self._show_ieps = None
        self._number = None
        self._account = None
        self._payments = None
        self._serie = None
        self.discriminator = None

        self.currency_id = currency_id
        self.client_id = client_id
        self.location_id = location_id
        self.warehouse_id = warehouse_id
        self.cfdi_use = cfdi_use
        self.invoice_date = invoice_date
        self.price_list_id = price_list_id
        if exchange_rate is not None:
            self.exchange_rate = exchange_rate
        if isr_ret_rate is not None:
            self.isr_ret_rate = isr_ret_rate
        if vat_ret_rate is not None:
            self.vat_ret_rate = vat_ret_rate
        if comments is not None:
            self.comments = comments
        if vat_rate is not None:
            self.vat_rate = vat_rate
        if discount_type is not None:
            self.discount_type = discount_type
        if discount_amount is not None:
            self.discount_amount = discount_amount
        if products is not None:
            self.products = products
        if services is not None:
            self.services = services
        if emails is not None:
            self.emails = emails
        if purchase_order is not None:
            self.purchase_order = purchase_order
        if credit_days is not None:
            self.credit_days = credit_days
        if is_fiscal_invoice is not None:
            self.is_fiscal_invoice = is_fiscal_invoice
        if show_ieps is not None:
            self.show_ieps = show_ieps
        if number is not None:
            self.number = number
        if account is not None:
            self.account = account
        if payments is not None:
            self.payments = payments
        if serie is not None:
            self.serie = serie

    @property
    def currency_id(self):
        """Gets the currency_id of this NewInvoice.  # noqa: E501


        :return: The currency_id of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._currency_id

    @currency_id.setter
    def currency_id(self, currency_id):
        """Sets the currency_id of this NewInvoice.


        :param currency_id: The currency_id of this NewInvoice.  # noqa: E501
        :type: str
        """
        if currency_id is None:
            raise ValueError("Invalid value for `currency_id`, must not be `None`")  # noqa: E501

        self._currency_id = currency_id

    @property
    def client_id(self):
        """Gets the client_id of this NewInvoice.  # noqa: E501


        :return: The client_id of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this NewInvoice.


        :param client_id: The client_id of this NewInvoice.  # noqa: E501
        :type: str
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def location_id(self):
        """Gets the location_id of this NewInvoice.  # noqa: E501


        :return: The location_id of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._location_id

    @location_id.setter
    def location_id(self, location_id):
        """Sets the location_id of this NewInvoice.


        :param location_id: The location_id of this NewInvoice.  # noqa: E501
        :type: str
        """
        if location_id is None:
            raise ValueError("Invalid value for `location_id`, must not be `None`")  # noqa: E501

        self._location_id = location_id

    @property
    def warehouse_id(self):
        """Gets the warehouse_id of this NewInvoice.  # noqa: E501


        :return: The warehouse_id of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._warehouse_id

    @warehouse_id.setter
    def warehouse_id(self, warehouse_id):
        """Sets the warehouse_id of this NewInvoice.


        :param warehouse_id: The warehouse_id of this NewInvoice.  # noqa: E501
        :type: str
        """
        if warehouse_id is None:
            raise ValueError("Invalid value for `warehouse_id`, must not be `None`")  # noqa: E501

        self._warehouse_id = warehouse_id

    @property
    def cfdi_use(self):
        """Gets the cfdi_use of this NewInvoice.  # noqa: E501


        :return: The cfdi_use of this NewInvoice.  # noqa: E501
        :rtype: int
        """
        return self._cfdi_use

    @cfdi_use.setter
    def cfdi_use(self, cfdi_use):
        """Sets the cfdi_use of this NewInvoice.


        :param cfdi_use: The cfdi_use of this NewInvoice.  # noqa: E501
        :type: int
        """
        if cfdi_use is None:
            raise ValueError("Invalid value for `cfdi_use`, must not be `None`")  # noqa: E501

        self._cfdi_use = cfdi_use

    @property
    def invoice_date(self):
        """Gets the invoice_date of this NewInvoice.  # noqa: E501


        :return: The invoice_date of this NewInvoice.  # noqa: E501
        :rtype: datetime
        """
        return self._invoice_date

    @invoice_date.setter
    def invoice_date(self, invoice_date):
        """Sets the invoice_date of this NewInvoice.


        :param invoice_date: The invoice_date of this NewInvoice.  # noqa: E501
        :type: datetime
        """
        if invoice_date is None:
            raise ValueError("Invalid value for `invoice_date`, must not be `None`")  # noqa: E501

        self._invoice_date = invoice_date

    @property
    def price_list_id(self):
        """Gets the price_list_id of this NewInvoice.  # noqa: E501


        :return: The price_list_id of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._price_list_id

    @price_list_id.setter
    def price_list_id(self, price_list_id):
        """Sets the price_list_id of this NewInvoice.


        :param price_list_id: The price_list_id of this NewInvoice.  # noqa: E501
        :type: str
        """
        if price_list_id is None:
            raise ValueError("Invalid value for `price_list_id`, must not be `None`")  # noqa: E501

        self._price_list_id = price_list_id

    @property
    def exchange_rate(self):
        """Gets the exchange_rate of this NewInvoice.  # noqa: E501


        :return: The exchange_rate of this NewInvoice.  # noqa: E501
        :rtype: float
        """
        return self._exchange_rate

    @exchange_rate.setter
    def exchange_rate(self, exchange_rate):
        """Sets the exchange_rate of this NewInvoice.


        :param exchange_rate: The exchange_rate of this NewInvoice.  # noqa: E501
        :type: float
        """

        self._exchange_rate = exchange_rate

    @property
    def isr_ret_rate(self):
        """Gets the isr_ret_rate of this NewInvoice.  # noqa: E501


        :return: The isr_ret_rate of this NewInvoice.  # noqa: E501
        :rtype: float
        """
        return self._isr_ret_rate

    @isr_ret_rate.setter
    def isr_ret_rate(self, isr_ret_rate):
        """Sets the isr_ret_rate of this NewInvoice.


        :param isr_ret_rate: The isr_ret_rate of this NewInvoice.  # noqa: E501
        :type: float
        """

        self._isr_ret_rate = isr_ret_rate

    @property
    def vat_ret_rate(self):
        """Gets the vat_ret_rate of this NewInvoice.  # noqa: E501


        :return: The vat_ret_rate of this NewInvoice.  # noqa: E501
        :rtype: float
        """
        return self._vat_ret_rate

    @vat_ret_rate.setter
    def vat_ret_rate(self, vat_ret_rate):
        """Sets the vat_ret_rate of this NewInvoice.


        :param vat_ret_rate: The vat_ret_rate of this NewInvoice.  # noqa: E501
        :type: float
        """

        self._vat_ret_rate = vat_ret_rate

    @property
    def comments(self):
        """Gets the comments of this NewInvoice.  # noqa: E501


        :return: The comments of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._comments

    @comments.setter
    def comments(self, comments):
        """Sets the comments of this NewInvoice.


        :param comments: The comments of this NewInvoice.  # noqa: E501
        :type: str
        """

        self._comments = comments

    @property
    def vat_rate(self):
        """Gets the vat_rate of this NewInvoice.  # noqa: E501


        :return: The vat_rate of this NewInvoice.  # noqa: E501
        :rtype: float
        """
        return self._vat_rate

    @vat_rate.setter
    def vat_rate(self, vat_rate):
        """Sets the vat_rate of this NewInvoice.


        :param vat_rate: The vat_rate of this NewInvoice.  # noqa: E501
        :type: float
        """

        self._vat_rate = vat_rate

    @property
    def discount_type(self):
        """Gets the discount_type of this NewInvoice.  # noqa: E501


        :return: The discount_type of this NewInvoice.  # noqa: E501
        :rtype: int
        """
        return self._discount_type

    @discount_type.setter
    def discount_type(self, discount_type):
        """Sets the discount_type of this NewInvoice.


        :param discount_type: The discount_type of this NewInvoice.  # noqa: E501
        :type: int
        """

        self._discount_type = discount_type

    @property
    def discount_amount(self):
        """Gets the discount_amount of this NewInvoice.  # noqa: E501


        :return: The discount_amount of this NewInvoice.  # noqa: E501
        :rtype: float
        """
        return self._discount_amount

    @discount_amount.setter
    def discount_amount(self, discount_amount):
        """Sets the discount_amount of this NewInvoice.


        :param discount_amount: The discount_amount of this NewInvoice.  # noqa: E501
        :type: float
        """

        self._discount_amount = discount_amount

    @property
    def products(self):
        """Gets the products of this NewInvoice.  # noqa: E501


        :return: The products of this NewInvoice.  # noqa: E501
        :rtype: list[NewInvoiceProduct]
        """
        return self._products

    @products.setter
    def products(self, products):
        """Sets the products of this NewInvoice.


        :param products: The products of this NewInvoice.  # noqa: E501
        :type: list[NewInvoiceProduct]
        """

        self._products = products

    @property
    def services(self):
        """Gets the services of this NewInvoice.  # noqa: E501


        :return: The services of this NewInvoice.  # noqa: E501
        :rtype: list[NewInvoiceService]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this NewInvoice.


        :param services: The services of this NewInvoice.  # noqa: E501
        :type: list[NewInvoiceService]
        """

        self._services = services

    @property
    def emails(self):
        """Gets the emails of this NewInvoice.  # noqa: E501


        :return: The emails of this NewInvoice.  # noqa: E501
        :rtype: list[str]
        """
        return self._emails

    @emails.setter
    def emails(self, emails):
        """Sets the emails of this NewInvoice.


        :param emails: The emails of this NewInvoice.  # noqa: E501
        :type: list[str]
        """

        self._emails = emails

    @property
    def purchase_order(self):
        """Gets the purchase_order of this NewInvoice.  # noqa: E501


        :return: The purchase_order of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._purchase_order

    @purchase_order.setter
    def purchase_order(self, purchase_order):
        """Sets the purchase_order of this NewInvoice.


        :param purchase_order: The purchase_order of this NewInvoice.  # noqa: E501
        :type: str
        """

        self._purchase_order = purchase_order

    @property
    def credit_days(self):
        """Gets the credit_days of this NewInvoice.  # noqa: E501


        :return: The credit_days of this NewInvoice.  # noqa: E501
        :rtype: int
        """
        return self._credit_days

    @credit_days.setter
    def credit_days(self, credit_days):
        """Sets the credit_days of this NewInvoice.


        :param credit_days: The credit_days of this NewInvoice.  # noqa: E501
        :type: int
        """

        self._credit_days = credit_days

    @property
    def is_fiscal_invoice(self):
        """Gets the is_fiscal_invoice of this NewInvoice.  # noqa: E501


        :return: The is_fiscal_invoice of this NewInvoice.  # noqa: E501
        :rtype: bool
        """
        return self._is_fiscal_invoice

    @is_fiscal_invoice.setter
    def is_fiscal_invoice(self, is_fiscal_invoice):
        """Sets the is_fiscal_invoice of this NewInvoice.


        :param is_fiscal_invoice: The is_fiscal_invoice of this NewInvoice.  # noqa: E501
        :type: bool
        """

        self._is_fiscal_invoice = is_fiscal_invoice

    @property
    def show_ieps(self):
        """Gets the show_ieps of this NewInvoice.  # noqa: E501


        :return: The show_ieps of this NewInvoice.  # noqa: E501
        :rtype: bool
        """
        return self._show_ieps

    @show_ieps.setter
    def show_ieps(self, show_ieps):
        """Sets the show_ieps of this NewInvoice.


        :param show_ieps: The show_ieps of this NewInvoice.  # noqa: E501
        :type: bool
        """

        self._show_ieps = show_ieps

    @property
    def number(self):
        """Gets the number of this NewInvoice.  # noqa: E501


        :return: The number of this NewInvoice.  # noqa: E501
        :rtype: int
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this NewInvoice.


        :param number: The number of this NewInvoice.  # noqa: E501
        :type: int
        """

        self._number = number

    @property
    def account(self):
        """Gets the account of this NewInvoice.  # noqa: E501


        :return: The account of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._account

    @account.setter
    def account(self, account):
        """Sets the account of this NewInvoice.


        :param account: The account of this NewInvoice.  # noqa: E501
        :type: str
        """

        self._account = account

    @property
    def payments(self):
        """Gets the payments of this NewInvoice.  # noqa: E501


        :return: The payments of this NewInvoice.  # noqa: E501
        :rtype: list[NewInvoicePayment]
        """
        return self._payments

    @payments.setter
    def payments(self, payments):
        """Sets the payments of this NewInvoice.


        :param payments: The payments of this NewInvoice.  # noqa: E501
        :type: list[NewInvoicePayment]
        """

        self._payments = payments

    @property
    def serie(self):
        """Gets the serie of this NewInvoice.  # noqa: E501


        :return: The serie of this NewInvoice.  # noqa: E501
        :rtype: str
        """
        return self._serie

    @serie.setter
    def serie(self, serie):
        """Sets the serie of this NewInvoice.


        :param serie: The serie of this NewInvoice.  # noqa: E501
        :type: str
        """

        self._serie = serie

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NewInvoice):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
