# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.i_edm_model import IEdmModel  # noqa: F401,E501
from swagger_client.models.i_edm_type import IEdmType  # noqa: F401,E501


class ODataQueryContext(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model': 'IEdmModel',
        'element_type': 'IEdmType',
        'element_clr_type': 'str'
    }

    attribute_map = {
        'model': 'Model',
        'element_type': 'ElementType',
        'element_clr_type': 'ElementClrType'
    }

    def __init__(self, model=None, element_type=None, element_clr_type=None):  # noqa: E501
        """ODataQueryContext - a model defined in Swagger"""  # noqa: E501

        self._model = None
        self._element_type = None
        self._element_clr_type = None
        self.discriminator = None

        if model is not None:
            self.model = model
        if element_type is not None:
            self.element_type = element_type
        if element_clr_type is not None:
            self.element_clr_type = element_clr_type

    @property
    def model(self):
        """Gets the model of this ODataQueryContext.  # noqa: E501


        :return: The model of this ODataQueryContext.  # noqa: E501
        :rtype: IEdmModel
        """
        return self._model

    @model.setter
    def model(self, model):
        """Sets the model of this ODataQueryContext.


        :param model: The model of this ODataQueryContext.  # noqa: E501
        :type: IEdmModel
        """

        self._model = model

    @property
    def element_type(self):
        """Gets the element_type of this ODataQueryContext.  # noqa: E501


        :return: The element_type of this ODataQueryContext.  # noqa: E501
        :rtype: IEdmType
        """
        return self._element_type

    @element_type.setter
    def element_type(self, element_type):
        """Sets the element_type of this ODataQueryContext.


        :param element_type: The element_type of this ODataQueryContext.  # noqa: E501
        :type: IEdmType
        """

        self._element_type = element_type

    @property
    def element_clr_type(self):
        """Gets the element_clr_type of this ODataQueryContext.  # noqa: E501


        :return: The element_clr_type of this ODataQueryContext.  # noqa: E501
        :rtype: str
        """
        return self._element_clr_type

    @element_clr_type.setter
    def element_clr_type(self, element_clr_type):
        """Sets the element_clr_type of this ODataQueryContext.


        :param element_clr_type: The element_clr_type of this ODataQueryContext.  # noqa: E501
        :type: str
        """

        self._element_clr_type = element_clr_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ODataQueryContext):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
