# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class UserProfile(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_id': 'str',
        'company_name': 'str',
        'company_number': 'int',
        'email': 'str',
        'name': 'str',
        'rfc': 'str',
        'roles': 'list[str]',
        'user_id': 'str',
        'username': 'str'
    }

    attribute_map = {
        'company_id': 'CompanyID',
        'company_name': 'CompanyName',
        'company_number': 'CompanyNumber',
        'email': 'Email',
        'name': 'Name',
        'rfc': 'RFC',
        'roles': 'Roles',
        'user_id': 'UserID',
        'username': 'Username'
    }

    def __init__(self, company_id=None, company_name=None, company_number=None, email=None, name=None, rfc=None, roles=None, user_id=None, username=None):  # noqa: E501
        """UserProfile - a model defined in Swagger"""  # noqa: E501

        self._company_id = None
        self._company_name = None
        self._company_number = None
        self._email = None
        self._name = None
        self._rfc = None
        self._roles = None
        self._user_id = None
        self._username = None
        self.discriminator = None

        if company_id is not None:
            self.company_id = company_id
        if company_name is not None:
            self.company_name = company_name
        if company_number is not None:
            self.company_number = company_number
        if email is not None:
            self.email = email
        if name is not None:
            self.name = name
        if rfc is not None:
            self.rfc = rfc
        if roles is not None:
            self.roles = roles
        if user_id is not None:
            self.user_id = user_id
        if username is not None:
            self.username = username

    @property
    def company_id(self):
        """Gets the company_id of this UserProfile.  # noqa: E501


        :return: The company_id of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this UserProfile.


        :param company_id: The company_id of this UserProfile.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def company_name(self):
        """Gets the company_name of this UserProfile.  # noqa: E501


        :return: The company_name of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._company_name

    @company_name.setter
    def company_name(self, company_name):
        """Sets the company_name of this UserProfile.


        :param company_name: The company_name of this UserProfile.  # noqa: E501
        :type: str
        """

        self._company_name = company_name

    @property
    def company_number(self):
        """Gets the company_number of this UserProfile.  # noqa: E501


        :return: The company_number of this UserProfile.  # noqa: E501
        :rtype: int
        """
        return self._company_number

    @company_number.setter
    def company_number(self, company_number):
        """Sets the company_number of this UserProfile.


        :param company_number: The company_number of this UserProfile.  # noqa: E501
        :type: int
        """

        self._company_number = company_number

    @property
    def email(self):
        """Gets the email of this UserProfile.  # noqa: E501


        :return: The email of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this UserProfile.


        :param email: The email of this UserProfile.  # noqa: E501
        :type: str
        """

        self._email = email

    @property
    def name(self):
        """Gets the name of this UserProfile.  # noqa: E501


        :return: The name of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserProfile.


        :param name: The name of this UserProfile.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def rfc(self):
        """Gets the rfc of this UserProfile.  # noqa: E501


        :return: The rfc of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._rfc

    @rfc.setter
    def rfc(self, rfc):
        """Sets the rfc of this UserProfile.


        :param rfc: The rfc of this UserProfile.  # noqa: E501
        :type: str
        """

        self._rfc = rfc

    @property
    def roles(self):
        """Gets the roles of this UserProfile.  # noqa: E501


        :return: The roles of this UserProfile.  # noqa: E501
        :rtype: list[str]
        """
        return self._roles

    @roles.setter
    def roles(self, roles):
        """Sets the roles of this UserProfile.


        :param roles: The roles of this UserProfile.  # noqa: E501
        :type: list[str]
        """

        self._roles = roles

    @property
    def user_id(self):
        """Gets the user_id of this UserProfile.  # noqa: E501


        :return: The user_id of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._user_id

    @user_id.setter
    def user_id(self, user_id):
        """Sets the user_id of this UserProfile.


        :param user_id: The user_id of this UserProfile.  # noqa: E501
        :type: str
        """

        self._user_id = user_id

    @property
    def username(self):
        """Gets the username of this UserProfile.  # noqa: E501


        :return: The username of this UserProfile.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this UserProfile.


        :param username: The username of this UserProfile.  # noqa: E501
        :type: str
        """

        self._username = username

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
