# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class WebHookSubscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'event_id': 'str',
        'target_url': 'str',
        'event_name': 'str'
    }

    attribute_map = {
        'id': 'ID',
        'event_id': 'EventID',
        'target_url': 'TargetURL',
        'event_name': 'EventName'
    }

    def __init__(self, id=None, event_id=None, target_url=None, event_name=None):  # noqa: E501
        """WebHookSubscription - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._event_id = None
        self._target_url = None
        self._event_name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if event_id is not None:
            self.event_id = event_id
        if target_url is not None:
            self.target_url = target_url
        if event_name is not None:
            self.event_name = event_name

    @property
    def id(self):
        """Gets the id of this WebHookSubscription.  # noqa: E501


        :return: The id of this WebHookSubscription.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WebHookSubscription.


        :param id: The id of this WebHookSubscription.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def event_id(self):
        """Gets the event_id of this WebHookSubscription.  # noqa: E501


        :return: The event_id of this WebHookSubscription.  # noqa: E501
        :rtype: str
        """
        return self._event_id

    @event_id.setter
    def event_id(self, event_id):
        """Sets the event_id of this WebHookSubscription.


        :param event_id: The event_id of this WebHookSubscription.  # noqa: E501
        :type: str
        """

        self._event_id = event_id

    @property
    def target_url(self):
        """Gets the target_url of this WebHookSubscription.  # noqa: E501


        :return: The target_url of this WebHookSubscription.  # noqa: E501
        :rtype: str
        """
        return self._target_url

    @target_url.setter
    def target_url(self, target_url):
        """Sets the target_url of this WebHookSubscription.


        :param target_url: The target_url of this WebHookSubscription.  # noqa: E501
        :type: str
        """

        self._target_url = target_url

    @property
    def event_name(self):
        """Gets the event_name of this WebHookSubscription.  # noqa: E501


        :return: The event_name of this WebHookSubscription.  # noqa: E501
        :rtype: str
        """
        return self._event_name

    @event_name.setter
    def event_name(self, event_name):
        """Sets the event_name of this WebHookSubscription.


        :param event_name: The event_name of this WebHookSubscription.  # noqa: E501
        :type: str
        """

        self._event_name = event_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebHookSubscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
