# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class AccountingJournalsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def accounting_journals_add_accounting_journal(self, new_accounting_journal, **kwargs):  # noqa: E501
        """Agregar póliza contable  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_add_accounting_journal(new_accounting_journal, async=True)
        >>> result = thread.get()

        :param async bool
        :param NewAccountingJournal new_accounting_journal:  (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.accounting_journals_add_accounting_journal_with_http_info(new_accounting_journal, **kwargs)  # noqa: E501
        else:
            (data) = self.accounting_journals_add_accounting_journal_with_http_info(new_accounting_journal, **kwargs)  # noqa: E501
            return data

    def accounting_journals_add_accounting_journal_with_http_info(self, new_accounting_journal, **kwargs):  # noqa: E501
        """Agregar póliza contable  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_add_accounting_journal_with_http_info(new_accounting_journal, async=True)
        >>> result = thread.get()

        :param async bool
        :param NewAccountingJournal new_accounting_journal:  (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['new_accounting_journal']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method accounting_journals_add_accounting_journal" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'new_accounting_journal' is set
        if ('new_accounting_journal' not in params or
                params['new_accounting_journal'] is None):
            raise ValueError("Missing the required parameter `new_accounting_journal` when calling `accounting_journals_add_accounting_journal`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'new_accounting_journal' in params:
            body_params = params['new_accounting_journal']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/AccountingJournals', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def accounting_journals_delete_accounting_journal(self, id_list, **kwargs):  # noqa: E501
        """Eliminar póliza contable  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_delete_accounting_journal(id_list, async=True)
        >>> result = thread.get()

        :param async bool
        :param list[str] id_list:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.accounting_journals_delete_accounting_journal_with_http_info(id_list, **kwargs)  # noqa: E501
        else:
            (data) = self.accounting_journals_delete_accounting_journal_with_http_info(id_list, **kwargs)  # noqa: E501
            return data

    def accounting_journals_delete_accounting_journal_with_http_info(self, id_list, **kwargs):  # noqa: E501
        """Eliminar póliza contable  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_delete_accounting_journal_with_http_info(id_list, async=True)
        >>> result = thread.get()

        :param async bool
        :param list[str] id_list:  (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['id_list']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method accounting_journals_delete_accounting_journal" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'id_list' is set
        if ('id_list' not in params or
                params['id_list'] is None):
            raise ValueError("Missing the required parameter `id_list` when calling `accounting_journals_delete_accounting_journal`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'id_list' in params:
            body_params = params['id_list']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/AccountingJournals', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def accounting_journals_edit_accounting_journal(self, accounting_journal, **kwargs):  # noqa: E501
        """Editar póliza contable  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_edit_accounting_journal(accounting_journal, async=True)
        >>> result = thread.get()

        :param async bool
        :param EditAccountingJournal accounting_journal:  (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.accounting_journals_edit_accounting_journal_with_http_info(accounting_journal, **kwargs)  # noqa: E501
        else:
            (data) = self.accounting_journals_edit_accounting_journal_with_http_info(accounting_journal, **kwargs)  # noqa: E501
            return data

    def accounting_journals_edit_accounting_journal_with_http_info(self, accounting_journal, **kwargs):  # noqa: E501
        """Editar póliza contable  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_edit_accounting_journal_with_http_info(accounting_journal, async=True)
        >>> result = thread.get()

        :param async bool
        :param EditAccountingJournal accounting_journal:  (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['accounting_journal']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method accounting_journals_edit_accounting_journal" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'accounting_journal' is set
        if ('accounting_journal' not in params or
                params['accounting_journal'] is None):
            raise ValueError("Missing the required parameter `accounting_journal` when calling `accounting_journals_edit_accounting_journal`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'accounting_journal' in params:
            body_params = params['accounting_journal']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json', 'text/json', 'application/xml', 'text/xml', 'application/x-www-form-urlencoded'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/AccountingJournals', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def accounting_journals_get(self, **kwargs):  # noqa: E501
        """Obtiene la lista de pólizas contables.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_get(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: AccountingJournalPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.accounting_journals_get_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.accounting_journals_get_with_http_info(**kwargs)  # noqa: E501
            return data

    def accounting_journals_get_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de pólizas contables.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.accounting_journals_get_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: AccountingJournalPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'orderby', 'top', 'skip']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method accounting_journals_get" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('$filter', params['filter']))  # noqa: E501
        if 'orderby' in params:
            query_params.append(('$orderby', params['orderby']))  # noqa: E501
        if 'top' in params:
            query_params.append(('$top', params['top']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('$skip', params['skip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/AccountingJournals', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='AccountingJournalPage',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
