# coding: utf-8

"""
    Bind ERP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v1.2
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class CatalogsApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def catalogs_get_banks(self, **kwargs):  # noqa: E501
        """Obtiene la lista de bancos.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_banks(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: BankPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_banks_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_banks_with_http_info(**kwargs)  # noqa: E501
            return data

    def catalogs_get_banks_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de bancos.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_banks_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: BankPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'orderby', 'top', 'skip']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_banks" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('$filter', params['filter']))  # noqa: E501
        if 'orderby' in params:
            query_params.append(('$orderby', params['orderby']))  # noqa: E501
        if 'top' in params:
            query_params.append(('$top', params['top']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('$skip', params['skip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/Banks', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='BankPage',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def catalogs_get_categories(self, **kwargs):  # noqa: E501
        """Obtiene la lista de Categorias.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_categories(async=True)
        >>> result = thread.get()

        :param async bool
        :return: list[Category1]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_categories_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_categories_with_http_info(**kwargs)  # noqa: E501
            return data

    def catalogs_get_categories_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de Categorias.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_categories_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :return: list[Category1]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = []  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_categories" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/Categories', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Category1]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def catalogs_get_currencies(self, **kwargs):  # noqa: E501
        """Obtiene la lista de monedas.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_currencies(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: CurrencyPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_currencies_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_currencies_with_http_info(**kwargs)  # noqa: E501
            return data

    def catalogs_get_currencies_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de monedas.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_currencies_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: CurrencyPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'orderby', 'top', 'skip']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_currencies" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('$filter', params['filter']))  # noqa: E501
        if 'orderby' in params:
            query_params.append(('$orderby', params['orderby']))  # noqa: E501
        if 'top' in params:
            query_params.append(('$top', params['top']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('$skip', params['skip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/Currencies', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='CurrencyPage',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def catalogs_get_locations(self, **kwargs):  # noqa: E501
        """Obtiene la lista de sucursales.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_locations(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: LocationPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_locations_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_locations_with_http_info(**kwargs)  # noqa: E501
            return data

    def catalogs_get_locations_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de sucursales.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_locations_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: LocationPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'orderby', 'top', 'skip']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_locations" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('$filter', params['filter']))  # noqa: E501
        if 'orderby' in params:
            query_params.append(('$orderby', params['orderby']))  # noqa: E501
        if 'top' in params:
            query_params.append(('$top', params['top']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('$skip', params['skip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/Locations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='LocationPage',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def catalogs_get_price_lists(self, **kwargs):  # noqa: E501
        """Obtiene la lista de precios.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_price_lists(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: PriceListPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_price_lists_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_price_lists_with_http_info(**kwargs)  # noqa: E501
            return data

    def catalogs_get_price_lists_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de precios.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_price_lists_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: PriceListPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'orderby', 'top', 'skip']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_price_lists" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('$filter', params['filter']))  # noqa: E501
        if 'orderby' in params:
            query_params.append(('$orderby', params['orderby']))  # noqa: E501
        if 'top' in params:
            query_params.append(('$top', params['top']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('$skip', params['skip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/PriceLists', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='PriceListPage',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def catalogs_get_series(self, doc_type, **kwargs):  # noqa: E501
        """Obtiene la lista de Series.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_series(doc_type, async=True)
        >>> result = thread.get()

        :param async bool
        :param int doc_type: (required)
        :return: list[Series]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_series_with_http_info(doc_type, **kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_series_with_http_info(doc_type, **kwargs)  # noqa: E501
            return data

    def catalogs_get_series_with_http_info(self, doc_type, **kwargs):  # noqa: E501
        """Obtiene la lista de Series.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_series_with_http_info(doc_type, async=True)
        >>> result = thread.get()

        :param async bool
        :param int doc_type: (required)
        :return: list[Series]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['doc_type']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_series" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'doc_type' is set
        if ('doc_type' not in params or
                params['doc_type'] is None):
            raise ValueError("Missing the required parameter `doc_type` when calling `catalogs_get_series`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'doc_type' in params:
            query_params.append(('docType', params['doc_type']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json', 'application/xml', 'text/xml'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/Series', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[Series]',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def catalogs_get_users(self, **kwargs):  # noqa: E501
        """Obtiene la lista de usuarios.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_users(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: UserPage
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async'):
            return self.catalogs_get_users_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.catalogs_get_users_with_http_info(**kwargs)  # noqa: E501
            return data

    def catalogs_get_users_with_http_info(self, **kwargs):  # noqa: E501
        """Obtiene la lista de usuarios.  # noqa: E501

          # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async=True
        >>> thread = api.catalogs_get_users_with_http_info(async=True)
        >>> result = thread.get()

        :param async bool
        :param str filter: Filters the results, based on a Boolean condition.
        :param str orderby: Sorts the results.
        :param int top: Returns only the first n results.
        :param int skip: Skips the first n results.
        :return: UserPage
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['filter', 'orderby', 'top', 'skip']  # noqa: E501
        all_params.append('async')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method catalogs_get_users" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'filter' in params:
            query_params.append(('$filter', params['filter']))  # noqa: E501
        if 'orderby' in params:
            query_params.append(('$orderby', params['orderby']))  # noqa: E501
        if 'top' in params:
            query_params.append(('$top', params['top']))  # noqa: E501
        if 'skip' in params:
            query_params.append(('$skip', params['skip']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json', 'text/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/api/Users', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='UserPage',  # noqa: E501
            auth_settings=auth_settings,
            async=params.get('async'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
